name: CD SAP-Home frontend PRODUCTION

on:
  push:
    tags: ["*"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug environment variables
        run: echo "Image is ${{ vars.DOCKER_IMAGE_PROD}}"

      - name: Update Docker Container metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ vars.DOCKER_IMAGE_PROD}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCA's Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.production
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ vars.DOCKER_IMAGE_PROD}}:latest
            ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
            NEXT_PUBLIC_CONTENTFUL_PREVIEW=${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW }}
            NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN=${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_TOKEN }}
            NEXT_PUBLIC_CONTENTFUL_SPACE_ID=${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
  push-beta:
    needs: build-image
    runs-on: self-hosted

    steps:
      - name: Debug environment (Runner)
        run: echo "Image is ${{ vars.DOCKER_IMAGE_PROD}}"

      - name: Ensure docker network exists
        run: |
          DOCKER_NETWORK_NAME="${{ vars.NETWORK_NAME }}"
          if ! sudo docker network inspect "$DOCKER_NETWORK_NAME" >/dev/null 2>&1; then
            sudo docker network create "$DOCKER_NETWORK_NAME"
            echo "Created network: $DOCKER_NETWORK_NAME"
          else
            echo "Network already exists: $DOCKER_NETWORK_NAME"
          fi

      - name: Pull the latest production image
        run: sudo docker pull ${{ vars.DOCKER_IMAGE_PROD}}:latest

      - name: Stop existing container
        run: sudo docker rm -f ${{ vars.CONTAINER_NAME_PROD}} || true

      - name: Run the new production container
        run: sudo docker run --name ${{ vars.CONTAINER_NAME_PROD}} --restart unless-stopped -p ${{ vars.HOST_PORT_PROD}}:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_PROD}}:latest

      - name: Connect to the SAP network
        run: sudo docker network connect ${{ vars.NETWORK_NAME }} ${{ vars.CONTAINER_NAME_PROD}}

      - name: Prune unused Docker images
        run: sudo docker system prune -f
